import Colors from "./core-colors"
const Composition = {
    "color-text-default": Colors['base08'],
    "color-text-secondary": Colors['base07'],
    "color-text-inactive": Colors["base05"],
    "color-text-inverse": Colors["white"],
    "color-text-error": Colors["error06"],
    "color-text-warning": Colors["warning06"],
    "color-text-primary": Colors["primary06"],
    "color-text-info": Colors["info06"],
    "color-text-success": Colors["success06"],
    "color-text-placeholder": Colors["base04"],
    "color-border": Colors["base02"],
    "color-border-primary": Colors["primary06"],
    "color-border-error": Colors["error06"],
    "color-icon-inverse": Colors['white'],
    "color-icon-default": Colors["base06"],
    "color-icon-inactive": Colors["base05"],
    "color-icon-primary": Colors["primary06"],
    "color-background-titlebar": Colors["black"],
    "color-background-header": Colors["base08"],
    "color-background-base": Colors["base10"],
    "color-background-inactive": Colors["base02"],
    "color-background-section": Colors["base01"],
    "color-background-progressbar": Colors["base02"],
    "color-background-error": Colors["error06"],
    "color-background-success": Colors["success06"],
    "color-background-warning": Colors["warning06"],
    "color-background-section-warning": Colors["warning01"],
    "color-background-section-primary": Colors["primary01"],
    "color-background-section-error": Colors["error01"],
    "color-background-info": Colors["info08"],
    "color-background-white": Colors['white'],
    "color-background-button-hover": Colors["primary07"],
    "color-background-primary": Colors["primary06"],
    "color-highlight-progressbar": Colors["primary06"],
    "color-social-facebook": "#066efb",
    "color-social-google": "#4285f4",
    "color-checkbox-inactive": Colors["base08"],
    "color-background-section-info": Colors["info01"],
    "color-background-timeline": Colors["base03"],
    "color-background-section-primary2": Colors["primary02"],
    "color-background-OTP": Colors["info02"],
    "color-text-warning-2": Colors["warning04"],
};


export default Composition;